### PR TITLE
Adding the lookAt function in Entity makes it easy to control the view direction

### PR DESCRIPTION
**Pull request by LootSpace369**

### CODE REVIEW

**Comment by Sunch233** [comment]
Why would you want to add this

**Comment by Sunch233** [comment]
you can use `MobController::setLookPosition()` or `MobController::lookOffset` 
They have the same usage

**Comment by LootSpace369** [comment]
I think it would be better to put the control functions in the Entity file

**Comment by Sunch233** [comment]
I have no reason to refuse this, but you should note that this may conflict with AI

**Comment by LootSpace369** [comment]
I think not, if I have free time I will make a test video, I will close this pull request and resubmit next time

**Pull request merged**
